[package]
name = "folderSync"
version = "0.1.0"
authors = ["rkp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filetime = "0.2.7"